require('dotenv').config();
const express = require('express');
const session = require('express-session');
const flash = require('connect-flash');
const helmet = require('helmet');
const bcrypt = require('bcryptjs');
const multer = require('multer');
const path = require('path');
const { v4: uuidv4 } = require('uuid');
const crypto = require('crypto');
const { pool, initDb, hashToken, newApiKey } = require('./db');

const app = express();
const upload = multer({ dest: path.join(__dirname, 'tmp') });
const PORT = Number(process.env.PORT || 3000);
const BRAND = process.env.BRAND_NAME || 'OutbackServers Panel';
const API_PERMISSIONS = ['servers:list','provision:user','provision:server','server:start','server:stop','server:restart','console:read','console:command','backup:create','backup:download'];
const GAME_TYPES = ['PAPER','PURPUR','SPIGOT','BUKKIT','VANILLA','FORGE','FABRIC','QUILT','NEOFORGE','VELOCITY','WATERFALL','BUNGEECORD','RUST','VALHEIM','TERRARIA','FACTORIO','PALWORLD','CUSTOM'];
const GAME_VERSIONS = ['LATEST','1.21.11','1.21.10','1.21.8','1.21.4','1.21.1','1.20.6','1.20.4','1.20.1','1.19.4','1.18.2'];

app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(helmet({ contentSecurityPolicy:false }));
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.urlencoded({ extended:true, limit:'50mb' }));
app.use(express.json({ limit:'50mb' }));
app.use(session({ secret: process.env.SESSION_SECRET || 'dev-secret', resave:false, saveUninitialized:false, cookie:{ httpOnly:true, sameSite:'lax', maxAge:1000*60*60*12 } }));
app.use(flash());
app.use(async (req,res,next)=>{ res.locals.brand=BRAND; res.locals.flash={ error:req.flash('error'), success:req.flash('success') }; res.locals.user = req.session.userId ? await getUser(req.session.userId) : null; res.locals.gameTypes=GAME_TYPES; res.locals.gameVersions=GAME_VERSIONS; next(); });

async function getUser(id){ const r=await pool.query('SELECT * FROM users WHERE id=$1',[id]); return r.rows[0]||null; }
async function requireLogin(req,res,next){ if(!req.session.userId) return res.redirect('/login'); req.user=await getUser(req.session.userId); if(!req.user) return res.redirect('/login'); next(); }
async function requireAdmin(req,res,next){ await requireLogin(req,res,()=>{}); if(!req.user || req.user.role!=='admin') return res.status(403).render('error',{title:'Forbidden',message:'Admin only.'}); next(); }
async function canAccessService(user, serviceId){ if(user.role==='admin') return true; const own=await pool.query('SELECT id FROM services WHERE id=$1 AND owner_id=$2',[serviceId,user.id]); if(own.rows.length) return true; const sub=await pool.query('SELECT id FROM subusers WHERE service_id=$1 AND user_id=$2',[serviceId,user.id]); return !!sub.rows.length; }
async function audit(userId, action, details={}){ await pool.query('INSERT INTO audit_logs(id,user_id,action,details) VALUES($1,$2,$3,$4)',[uuidv4(),userId,action,details]); }
async function callAgent(node, route, opts={}){
  const res = await fetch(`${node.url.replace(/\/$/,'')}${route}`, { method: opts.method||'GET', headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${node.token}`, ...(opts.headers||{}) }, body: opts.body ? JSON.stringify(opts.body) : undefined });
  const text = await res.text(); let data; try{ data=JSON.parse(text); }catch{ data={raw:text}; }
  if(!res.ok) throw new Error(data.error || data.message || text || `Agent HTTP ${res.status}`);
  return data;
}
async function getNode(id){ const r=await pool.query('SELECT * FROM nodes WHERE id=$1',[id]); return r.rows[0]; }
async function getService(id){ const r=await pool.query('SELECT s.*, u.email owner_email, n.url node_url FROM services s LEFT JOIN users u ON u.id=s.owner_id LEFT JOIN nodes n ON n.id=s.node_id WHERE s.id=$1',[id]); return r.rows[0]; }
function requireApiPermission(permission){ return async (req,res,next)=>{
  const raw = (req.headers.authorization||'').replace(/^Bearer\s+/i,'') || req.headers['x-api-key'] || req.query.apiKey || '';
  if(!raw) return res.status(401).json({error:'API key required.'});
  const h=hashToken(raw); const r=await pool.query('SELECT k.*, u.role, u.email FROM api_keys k JOIN users u ON u.id=k.user_id WHERE token_hash=$1 AND revoked_at IS NULL',[h]);
  const key=r.rows[0]; if(!key) return res.status(401).json({error:'Invalid API key.'});
  if(!key.permissions.includes(permission)) return res.status(403).json({error:`API key missing permission: ${permission}`});
  await pool.query('UPDATE api_keys SET last_used_at=now() WHERE id=$1',[key.id]); req.apiKey=key; req.apiUser={id:key.user_id,role:key.role,email:key.email}; next();
};}

app.get('/', requireLogin, (req,res)=>res.redirect('/dashboard'));
app.get('/login',(req,res)=>res.render('login',{title:'Login'}));
app.post('/login', async (req,res)=>{ const r=await pool.query('SELECT * FROM users WHERE email=$1',[String(req.body.email||'').toLowerCase()]); const u=r.rows[0]; if(!u || !(await bcrypt.compare(req.body.password||'',u.password_hash))){ req.flash('error','Invalid login.'); return res.redirect('/login'); } req.session.userId=u.id; res.redirect('/dashboard'); });
app.post('/logout',(req,res)=>req.session.destroy(()=>res.redirect('/login')));

app.get('/dashboard', requireLogin, async (req,res)=>{ const services = req.user.role==='admin' ? (await pool.query('SELECT s.*, u.email owner_email FROM services s LEFT JOIN users u ON u.id=s.owner_id ORDER BY s.created_at DESC')).rows : (await pool.query('SELECT * FROM services WHERE owner_id=$1 ORDER BY created_at DESC',[req.user.id])).rows; res.render('dashboard',{title:'Dashboard',services}); });

app.get('/admin', requireAdmin, async (req,res)=>{ const [users,nodes,plans,auditRows]=await Promise.all([pool.query('SELECT * FROM users ORDER BY created_at DESC'), pool.query('SELECT * FROM nodes ORDER BY created_at DESC'), pool.query('SELECT * FROM plans ORDER BY created_at DESC'), pool.query('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 50')]); res.render('admin',{title:'Admin',users:users.rows,nodes:nodes.rows,plans:plans.rows,audit:auditRows.rows}); });
app.post('/admin/users', requireAdmin, async (req,res)=>{ try{ await pool.query('INSERT INTO users(id,email,name,role,password_hash,subdomain_slots,database_slots) VALUES($1,$2,$3,$4,$5,$6,$7)',[uuidv4(),req.body.email,req.body.name||req.body.email,req.body.role||'user',await bcrypt.hash(req.body.password||'ChangeMe123!',10),Number(req.body.subdomainSlots||0),Number(req.body.databaseSlots||0)]); req.flash('success','User added.'); }catch(e){req.flash('error',e.message)} res.redirect('/admin#users'); });
app.post('/admin/users/:id/slots', requireAdmin, async (req,res)=>{ await pool.query('UPDATE users SET subdomain_slots=$1,database_slots=$2 WHERE id=$3',[Number(req.body.subdomainSlots||0),Number(req.body.databaseSlots||0),req.params.id]); res.redirect('/admin#users'); });
app.post('/admin/nodes', requireAdmin, async (req,res)=>{ await pool.query('INSERT INTO nodes(id,name,url,token,public_ip,location) VALUES($1,$2,$3,$4,$5,$6)',[uuidv4(),req.body.name,req.body.url,req.body.token,req.body.publicIp,req.body.location]); res.redirect('/admin#nodes'); });
app.post('/admin/plans', requireAdmin, async (req,res)=>{ await pool.query('INSERT INTO plans(id,name,kind,price_cents,currency,memory_mb,storage_mb,cpu_limit,server_type,game_version,docker_image,slots) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[uuidv4(),req.body.name,req.body.kind,Number(req.body.priceCents||0),req.body.currency||'AUD',Number(req.body.memoryMb||1024),Number(req.body.storageMb||10240),Number(req.body.cpuLimit||1),req.body.serverType||null,req.body.gameVersion||null,req.body.dockerImage||null,{ subdomains:Number(req.body.subdomainSlots||0), databases:Number(req.body.databaseSlots||0) }]); res.redirect('/admin#plans'); });
app.post('/admin/plans/:id/delete', requireAdmin, async (req,res)=>{ await pool.query('DELETE FROM plans WHERE id=$1',[req.params.id]); res.redirect('/admin#plans'); });
app.post('/admin/provision', requireAdmin, async (req,res)=>{ try{ const plan=(await pool.query('SELECT * FROM plans WHERE id=$1',[req.body.planId])).rows[0]; const user=(await pool.query('SELECT * FROM users WHERE id=$1',[req.body.ownerId])).rows[0]; const node=(await pool.query('SELECT * FROM nodes WHERE id=$1',[req.body.nodeId])).rows[0]; if(!plan||!user||!node) throw new Error('Pick user, plan, and node.'); const body={ name:req.body.name||plan.name, serverType:req.body.serverType||plan.server_type, version:req.body.gameVersion||plan.game_version, image:plan.docker_image, memoryMb:plan.memory_mb, storageMb:plan.storage_mb, cpuLimit:plan.cpu_limit, port:req.body.port }; const created = plan.kind==='vps' ? await callAgent(node,'/services/vps',{method:'POST',body:{...body,username:user.email.split('@')[0]}}) : await callAgent(node,'/services/game',{method:'POST',body}); const svc=created.service; await pool.query('INSERT INTO services(id,owner_id,node_id,plan_id,agent_service_id,kind,name,status,server_type,game_version,docker_image,ip_address,port,memory_mb,storage_mb,cpu_limit,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)',[uuidv4(),user.id,node.id,plan.id,svc.id,plan.kind,svc.name,'running',svc.serverType||body.serverType,svc.version||body.version,svc.image,node.public_ip,svc.port,svc.memoryMb,svc.storageMb,plan.cpu_limit,svc]); req.flash('success','Service created.'); }catch(e){ req.flash('error',e.message); } res.redirect('/admin'); });

app.get('/api-keys', requireLogin, async (req,res)=>{ const users=req.user.role==='admin' ? (await pool.query('SELECT id,email,name FROM users ORDER BY email')).rows : [req.user]; const keys=(await pool.query('SELECT * FROM api_keys WHERE user_id=$1 OR $2 ORDER BY created_at DESC',[req.user.id,req.user.role==='admin'])).rows; res.render('api-keys',{title:'API Keys',users,keys,permissions:API_PERMISSIONS}); });
app.post('/api-keys', requireLogin, async (req,res)=>{ const token=newApiKey(); const target=req.user.role==='admin' && req.body.userId ? req.body.userId : req.user.id; const perms=Array.isArray(req.body.permissions)?req.body.permissions:(req.body.permissions?[req.body.permissions]:[]); await pool.query('INSERT INTO api_keys(id,user_id,name,prefix,token_hash,permissions) VALUES($1,$2,$3,$4,$5,$6)',[uuidv4(),target,req.body.name||'API Key',token.slice(0,12),hashToken(token),perms.filter(p=>API_PERMISSIONS.includes(p))]); req.flash('success',`API key created. Copy now: ${token}`); res.redirect('/api-keys'); });
app.post('/api-keys/:id/delete', requireLogin, async (req,res)=>{ await pool.query('UPDATE api_keys SET revoked_at=now() WHERE id=$1 AND (user_id=$2 OR $3)',[req.params.id,req.user.id,req.user.role==='admin']); res.redirect('/api-keys'); });

app.get('/services/:id', requireLogin, async (req,res)=>{ if(!(await canAccessService(req.user,req.params.id))) return res.status(403).render('error',{title:'Forbidden',message:'No access.'}); const service=await getService(req.params.id); const node=await getNode(service.node_id); const [subs,ports,dbs,subusers,users]=await Promise.all([pool.query('SELECT * FROM subdomains WHERE service_id=$1',[service.id]),pool.query('SELECT * FROM network_ports WHERE service_id=$1',[service.id]),pool.query('SELECT * FROM databases WHERE service_id=$1',[service.id]),pool.query('SELECT su.*, u.email FROM subusers su JOIN users u ON u.id=su.user_id WHERE service_id=$1',[service.id]),pool.query('SELECT id,email,name FROM users ORDER BY email')]); let live={}; try{ live=await callAgent(node,`/services/${service.agent_service_id}`); }catch(e){ live={error:e.message}; } res.render('service',{title:service.name,service,node,live,subs:subs.rows,ports:ports.rows,databases:dbs.rows,subusers:subusers.rows,users:users.rows,rootDomain:process.env.PUBLIC_ROOT_DOMAIN||''}); });
async function serviceAction(req,res,route,body={}){ try{ const service=await getService(req.params.id); const node=await getNode(service.node_id); await callAgent(node,`/services/${service.agent_service_id}${route}`,{method:'POST',body}); req.flash('success','Action completed.'); }catch(e){ req.flash('error',e.message); } res.redirect(`/services/${req.params.id}`); }
app.post('/services/:id/start', requireLogin, (req,res)=>serviceAction(req,res,'/start'));
app.post('/services/:id/stop', requireLogin, (req,res)=>serviceAction(req,res,'/stop'));
app.post('/services/:id/restart', requireLogin, (req,res)=>serviceAction(req,res,'/restart'));
app.post('/services/:id/factory-reset', requireLogin, (req,res)=>serviceAction(req,res,'/factory-reset'));
app.post('/services/:id/delete', requireLogin, async (req,res)=>{ try{ const service=await getService(req.params.id); const node=await getNode(service.node_id); await callAgent(node,`/services/${service.agent_service_id}/delete`,{method:'POST',body:{deleteFiles:req.body.deleteFiles==='true'}}); await pool.query('DELETE FROM services WHERE id=$1',[service.id]); req.flash('success','Deleted.'); }catch(e){req.flash('error',e.message)} res.redirect('/dashboard'); });
app.get('/services/:id/logs.json', requireLogin, async (req,res)=>{ const s=await getService(req.params.id); const n=await getNode(s.node_id); res.json(await callAgent(n,`/services/${s.agent_service_id}/logs?lines=${req.query.lines||500}`)); });
app.get('/services/:id/stats.json', requireLogin, async (req,res)=>{ const s=await getService(req.params.id); const n=await getNode(s.node_id); res.json(await callAgent(n,`/services/${s.agent_service_id}/stats`)); });
app.post('/services/:id/command', requireLogin, async (req,res)=>{ try{ const s=await getService(req.params.id); const n=await getNode(s.node_id); const out=await callAgent(n,`/services/${s.agent_service_id}/command`,{method:'POST',body:{command:req.body.command}}); res.json(out); }catch(e){ res.status(500).json({error:e.message}); } });
app.get('/services/:id/files.json', requireLogin, async (req,res)=>{ const s=await getService(req.params.id); const n=await getNode(s.node_id); res.json(await callAgent(n,`/services/${s.agent_service_id}/files?path=${encodeURIComponent(req.query.path||'')}`)); });
app.get('/services/:id/files/download', requireLogin, async (req,res)=>{ const s=await getService(req.params.id); const n=await getNode(s.node_id); const url=`${n.url.replace(/\/$/,'')}/services/${s.agent_service_id}/files/download?path=${encodeURIComponent(req.query.path||'')}`; const r=await fetch(url,{headers:{Authorization:`Bearer ${n.token}`}}); res.setHeader('Content-Disposition',r.headers.get('content-disposition')||'attachment'); r.body.pipe(res); });
app.post('/services/:id/files/delete', requireLogin, async (req,res)=>serviceAction(req,res,'/files/delete',{paths:Array.isArray(req.body.paths)?req.body.paths:[req.body.path]}));
app.post('/services/:id/backups/create', requireLogin, async (req,res)=>serviceAction(req,res,'/backups'));
app.get('/services/:id/backups.json', requireLogin, async (req,res)=>{ const s=await getService(req.params.id); const n=await getNode(s.node_id); res.json(await callAgent(n,`/services/${s.agent_service_id}/backups`)); });
app.post('/services/:id/network', requireLogin, async (req,res)=>{ await pool.query('INSERT INTO network_ports(id,service_id,port,protocol,notes) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[uuidv4(),req.params.id,Number(req.body.port),req.body.protocol||'tcp',req.body.notes||'']); res.redirect(`/services/${req.params.id}#network`); });
app.post('/services/:id/subdomains', requireLogin, async (req,res)=>{ const svc=await getService(req.params.id); const user=await getUser(svc.owner_id); const count=(await pool.query('SELECT count(*)::int c FROM subdomains sd JOIN services s ON s.id=sd.service_id WHERE s.owner_id=$1',[user.id])).rows[0].c; if(user.role!=='admin' && count>=user.subdomain_slots){ req.flash('error','No subdomain slots left.'); return res.redirect(`/services/${req.params.id}#subdomains`); } const root=process.env.PUBLIC_ROOT_DOMAIN||''; const hostname=req.body.useOwnDomain==='true'?req.body.hostname:`${req.body.prefix}.${root}`; await pool.query('INSERT INTO subdomains(id,service_id,hostname,target,port,owner_domain,status) VALUES($1,$2,$3,$4,$5,$6,$7)',[uuidv4(),req.params.id,hostname,req.body.target||svc.ip_address,Number(req.body.port||svc.port),req.body.useOwnDomain==='true','manual-dns']); res.redirect(`/services/${req.params.id}#subdomains`); });
app.post('/services/:id/databases', requireLogin, async (req,res)=>{ const svc=await getService(req.params.id); const user=await getUser(svc.owner_id); const existing=(await pool.query('SELECT id FROM databases WHERE service_id=$1',[svc.id])).rows.length; if(existing){ req.flash('error','Only one database per server.'); return res.redirect(`/services/${svc.id}#databases`); } if(user.role!=='admin' && user.database_slots<1){ req.flash('error','No database slots.'); return res.redirect(`/services/${svc.id}#databases`); } const pass=crypto.randomBytes(12).toString('hex'); await pool.query('INSERT INTO databases(id,service_id,name,engine,username,password,host,port) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[uuidv4(),svc.id,req.body.name||`db_${svc.id.toString().slice(0,8)}`,req.body.engine||'postgres',req.body.username||'server_user',pass,req.body.host||'localhost',Number(req.body.port||5432)]); res.redirect(`/services/${svc.id}#databases`); });
app.post('/services/:id/subusers', requireLogin, async (req,res)=>{ const perms=Array.isArray(req.body.permissions)?req.body.permissions:(req.body.permissions?[req.body.permissions]:[]); await pool.query('INSERT INTO subusers(id,service_id,user_id,permissions) VALUES($1,$2,$3,$4) ON CONFLICT(service_id,user_id) DO UPDATE SET permissions=$4',[uuidv4(),req.params.id,req.body.userId,perms]); res.redirect(`/services/${req.params.id}#subusers`); });

app.get('/api/health',(req,res)=>res.json({ok:true,brand:BRAND}));
app.get('/api/v1/plans', async (req,res)=>res.json({plans:(await pool.query('SELECT * FROM plans WHERE enabled=true')).rows}));
app.post('/api/v1/provision/order', requireApiPermission('provision:server'), async (req,res)=>{ try{ let user=(await pool.query('SELECT * FROM users WHERE email=$1',[req.body.email])).rows[0]; if(!user){ if(!req.apiKey.permissions.includes('provision:user')) return res.status(403).json({error:'API key missing permission: provision:user'}); const id=uuidv4(); await pool.query('INSERT INTO users(id,email,name,role,password_hash,subdomain_slots,database_slots) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,req.body.email,req.body.name||req.body.username||req.body.email,'user',await bcrypt.hash(req.body.password||crypto.randomBytes(8).toString('hex'),10),0,0]); user=(await pool.query('SELECT * FROM users WHERE id=$1',[id])).rows[0]; }
  const node=(await pool.query('SELECT * FROM nodes ORDER BY created_at LIMIT 1')).rows[0]; if(!node) return res.status(400).json({error:'No node exists.'}); const body={name:req.body.serverName||req.body.name||`${user.name}-server`,serverType:req.body.serverType||req.body.type||'PAPER',version:req.body.version||req.body.gameVersion||'LATEST',memoryMb:req.body.memoryMb||2048,storageMb:req.body.storageLimitMb||req.body.storageMb||10240,cpuLimit:req.body.cpuLimit||1,port:req.body.port||25565,image:req.body.image}; const created=await callAgent(node,'/services/game',{method:'POST',body}); const svc=created.service; const id=uuidv4(); await pool.query('INSERT INTO services(id,owner_id,node_id,agent_service_id,kind,name,status,server_type,game_version,docker_image,ip_address,port,memory_mb,storage_mb,cpu_limit,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)',[id,user.id,node.id,svc.id,'game',svc.name,'running',svc.serverType,svc.version,svc.image,node.public_ip,svc.port,svc.memoryMb,svc.storageMb,body.cpuLimit,svc]); res.json({ok:true,user:{id:user.id,email:user.email},server:{id,agentServiceId:svc.id,name:svc.name}}); }catch(e){ res.status(500).json({error:e.message}); } });

initDb().then(()=>{ if(process.argv.includes('--init-only')) process.exit(0); app.listen(PORT,()=>console.log(`${BRAND} running on http://localhost:${PORT}`)); }).catch(e=>{ console.error(e); process.exit(1); });
